[package]
name = "finger"
version = "0.1.0"
edition = "2021"

[dependencies]
finger-core = { path = "../finger-core" }
finger-tui = { path = "../finger-tui" }
anyhow = "1"
crossterm = "0.28"
ratatui = "0.28"
